### ISSUE TITLE
Instructions for Firefox

### ISSUE THREAD

**Issue by vilim** [fpopic/linux-egradjani#6]
To get modutil I needed to install `libnss3-tools` which were not present. 

That still did not end up working, but the instructions from [here](https://hr.comp.os.linux.narkive.com/7ObBGSco/eoi-na-ubuntu) did help, adding the eOI driver via the Firefox setting in particular seemed to do the trick (other steps described here might not have been strictly necessary in my case)

**Comment by fpopic** [comment]
Hmm, will try to include content of Debugging.md page directly in Readme.md and update with your suggestion! Thank you!

**Comment by fpopic** [comment]
Added note to readme and refactored readme. Thank you!
